#!/bin/bash
# Download GGUF from HuggingFace, add to preset with template.
# Usage: hf-to-llamacpp.sh <owner/project> <quant>
# Example: hf-to-llamacpp.sh unsloth/Qwen3.5-9B-GGUF IQ3_XXS
# Example: hf-to-llamacpp.sh bartowski/Qwen3-14B-NT-GGUF UD-IQ3_XXS

set -e
repo="${1:?Usage: hf-to-llamacpp.sh <owner/project> <quant>}"
quant="${2:?Usage: hf-to-llamacpp.sh <owner/project> <quant>}"

OUT_DIR="${LLAMACPP_MODELS:-$HOME/Applications/llamacpp/models}"
LLAMACPP="${LLAMACPP_ROOT:-$HOME/Applications/llamacpp}"
PRESET_FILE="$OUT_DIR/models.ini"

# Infer template from repo name (owner/project)
infer_template() {
  local r="$1"
  case "$r" in
    *[Qq]wen*) echo "chatml";;
    *[Mm]inistral*|*[Mm]istral*) echo "mistral-v3";;
    *[Ll]lama*) echo "llama3";;
    *[Dd]eep[Ss]eek*) echo "deepseek";;
    *[Gg]emma*) echo "gemma";;
    *[Pp]hi*) echo "phi3";;
    *) echo "chatml";;
  esac
}

# Ensure preset has [*] if empty
ensure_preset() {
  if [ ! -f "$PRESET_FILE" ] || ! grep -q '^\s*\[\*\]' "$PRESET_FILE" 2>/dev/null; then
    mkdir -p "$OUT_DIR"
    echo "; Generated by hf-to-llamacpp.sh" > "$PRESET_FILE"
    echo "[*]" >> "$PRESET_FILE"
    echo "n-gpu-layers = all" >> "$PRESET_FILE"
    echo "jinja = true" >> "$PRESET_FILE"
    echo "" >> "$PRESET_FILE"
  fi
}

# Find GGUF filename matching quant (case-insensitive)
find_gguf() {
  python3 -c "
import sys
try:
    from huggingface_hub import list_repo_files
    files = list_repo_files('$repo')
except Exception as e:
    import urllib.request, json
    r = urllib.request.urlopen('https://huggingface.co/api/models/$repo/tree/main')
    files = [f['path'] for f in json.loads(r.read().decode()) if f.get('type')=='file']
quant = '$quant'.upper()
for f in files:
    if f.endswith('.gguf') and quant in f.upper() and 'mmproj' not in f.lower():
        print(f)
        break
else:
    sys.exit(1)
"
}

# Download via llama-cli (uses cache, then we copy) or hf_hub_download
download_gguf() {
  local filepath="$1"
  local dest="$2"
  [ -f "$dest" ] && { echo "Already exists: $dest"; return; }
  mkdir -p "$OUT_DIR"
  python3 -c "
from huggingface_hub import hf_hub_download
import shutil
path = hf_hub_download(repo_id='$repo', filename='$filepath')
shutil.copy(path, '$dest')
" || { echo "Install: pip install huggingface_hub"; exit 1; }
}

filename=$(find_gguf) || { echo "No GGUF matching quant '$quant' in $repo"; exit 1; }
base=$(basename "$filename")
modelBaseRaw="${base%.gguf}"
# Remove suffixes for final name (match hf_ollama in ~/.bash_functions)
modelBase=$(echo "$modelBaseRaw" | sed -E 's/-(instruct|thinking|GGUF)//gi')
dest="$OUT_DIR/${modelBase}.gguf"
template=$(infer_template "$repo")

ensure_preset
download_gguf "$filename" "$dest"

# Add to preset if not already
if ! grep -q "^\[$modelBase\]" "$PRESET_FILE" 2>/dev/null; then
  echo "[$modelBase]" >> "$PRESET_FILE"
  echo "chat-template = $template" >> "$PRESET_FILE"
  echo "" >> "$PRESET_FILE"
  echo "Added to preset: $modelBase -> $template"
fi

echo "Done: $dest"
echo "Restart: systemctl --user restart llamacpp-server.service"
