#!/bin/bash
# Download GGUF from HuggingFace to llama.cpp models dir.
# Mimics hf_ollama from ~/.bash_functions but downloads directly to llama.cpp.
#
# USAGE:
#   hf.sh <owner/project> [quant] [custom_name]
#
# EXAMPLES:
#   hf.sh unsloth/Qwen3.5-9B-GGUF IQ3_XXS
#   hf.sh bartowski/Qwen3-14B-NT-GGUF UD-IQ3_XXS
#   hf.sh unsloth/Qwen3.5-9B-GGUF:Q4_K_XL
#   hf.sh unsloth/Qwen3.5-9B-GGUF IQ3_XXS MyCustomName:Tag
#
# Supports:
#   - Quantization tag as 2nd arg OR in repo path (owner/project:quant)
#   - Optional custom name as 3rd arg (preserves multiple colons)
#   - Auto-infers chat template from repo name
#   - Downloads full GGUF to ~/Applications/llamacpp/models/

set -e

repo="${1:?Usage: hf.sh <owner/project> [quant] [custom_name]}"
quant="${2:-}"
custom_name="${3:-}"

OUT_DIR="${LLAMACPP_MODELS:-$HOME/Applications/llamacpp/models}"
LLAMACPP="${LLAMACPP_ROOT:-$HOME/Applications/llamacpp}"
PRESET_FILE="$OUT_DIR/models.ini"

# Handle quantization in repo path (e.g., owner/project:quant)
if [[ "$repo" == *:* && -z "$quant" ]]; then
  quant="${repo#*:}"
  repo="${repo%%:*}"
fi

# Infer template from repo name
infer_template() {
  local r="$1"
  case "$r" in
    *[Qq]wen*) echo "qwen";;
    *[Mm]inistral*|*[Mm]istral*) echo "mistral-v3";;
    *[Ll]lama*) echo "llama3";;
    *[Dd]eep[Ss]eek*) echo "deepseek";;
    *[Gg]emma*) echo "gemma";;
    *[Pp]hi*) echo "phi3";;
    *) echo "chatml";;
  esac
}

# Ensure preset has [*] section
ensure_preset() {
  if [ ! -f "$PRESET_FILE" ] || ! grep -q '^\s*\[\*\]' "$PRESET_FILE" 2>/dev/null; then
    mkdir -p "$OUT_DIR"
    echo "; Generated by hf.sh" > "$PRESET_FILE"
    echo "[*]" >> "$PRESET_FILE"
    echo "n-gpu-layers = all" >> "$PRESET_FILE"
    echo "jinja = true" >> "$PRESET_FILE"
    echo "" >> "$PRESET_FILE"
  fi
}

# Find GGUF filename matching quant (case-insensitive)
find_gguf() {
  python3 -c "
import sys
try:
    from huggingface_hub import list_repo_files
    files = list_repo_files('$repo')
except Exception as e:
    import urllib.request, json
    r = urllib.request.urlopen('https://huggingface.co/api/models/$repo/tree/main')
    files = [f['path'] for f in json.loads(r.read().decode()) if f.get('type')=='file']
quant = '$quant'.upper()
for f in files:
    if f.endswith('.gguf') and quant in f.upper() and 'mmproj' not in f.lower():
        print(f)
        break
else:
    sys.exit(1)
"
}

# Download GGUF from HF
download_gguf() {
  local filepath="$1"
  local dest="$2"
  [ -f "$dest" ] && { echo "Already exists: $dest"; return; }
  mkdir -p "$OUT_DIR"
  echo "Downloading $filepath from $repo..."
  python3 -c "
from huggingface_hub import hf_hub_download
import shutil
path = hf_hub_download(repo_id='$repo', filename='$filepath')
shutil.copy(path, '$dest')
" || { echo "Install: pip install huggingface_hub"; exit 1; }
}

# Validate quant provided
if [ -z "$quant" ]; then
  echo "Error: quantization tag required"
  echo "Usage: hf.sh <owner/project> <quant> [custom_name]"
  echo "Example: hf.sh unsloth/Qwen3.5-9B-GGUF IQ3_XXS"
  exit 1
fi

# Find and download GGUF
filename=$(find_gguf) || { echo "No GGUF matching quant '$quant' in $repo"; exit 1; }
base=$(basename "$filename")
modelBaseRaw="${base%.gguf}"

# Determine final model name
if [ -n "$custom_name" ]; then
  modelBase="$custom_name"
else
  # Remove suffixes like hf_ollama does
  modelBase=$(echo "$modelBaseRaw" | sed -E 's/-(instruct|thinking|GGUF)//gi')
fi

dest="$OUT_DIR/${modelBase}.gguf"
template=$(infer_template "$repo")

ensure_preset
download_gguf "$filename" "$dest"

# Add to preset if not already
if ! grep -q "^\[$modelBase\]" "$PRESET_FILE" 2>/dev/null; then
  echo "[$modelBase]" >> "$PRESET_FILE"
  # Use qwen template file for Qwen models
  if [ "$template" = "qwen" ]; then
    echo "chat-template-file = models/templates/qwen.jinja" >> "$PRESET_FILE"
  else
    echo "chat-template = $template" >> "$PRESET_FILE"
  fi
  echo "" >> "$PRESET_FILE"
  echo "Added to preset: $modelBase -> $template"
fi

echo ""
echo "Done: $dest"
echo "Model will be available in router mode"
echo "Restart server to reload presets: systemctl --user restart llamacpp-server.service"
