#!/bin/bash
# Extract GGUF from Ollama, fetch Jinja templates, generate models.ini preset.
# Usage: ollama-to-llamacpp.sh <model:tag> [model:tag ...]
# Example: ollama-to-llamacpp.sh Qwen3.5-9B:UD-Q4_K_XL qwen3-vl:8b-instruct

set -e
OUT_DIR="${LLAMACPP_MODELS:-$HOME/Applications/llamacpp/models}"
LLAMACPP="${LLAMACPP_ROOT:-$HOME/Applications/llamacpp}"
TEMPLATES_DIR="$OUT_DIR/templates"
PRESET_FILE="$OUT_DIR/models.ini"

# Ollama system install: /usr/share/ollama; user: ~/.ollama
OLLAMA_BASE="${OLLAMA_MODELS:-}"
if [ -z "$OLLAMA_BASE" ]; then
  for base in /usr/share/ollama/.ollama/models "$HOME/.ollama/models"; do
    [ -d "$base/manifests" ] && { OLLAMA_BASE="$base"; break; }
  done
fi
[ -z "$OLLAMA_BASE" ] && { echo "Ollama models dir not found"; exit 1; }
MANIFEST_BASE="$OLLAMA_BASE/manifests/registry.ollama.ai/library"
BLOB_BASE="$OLLAMA_BASE/blobs"

need_sudo() { ! test -r "$BLOB_BASE" 2>/dev/null; }

# Model family -> template: built-in name, "qwen" (Jinja file), or HF repo for get_chat_template.py
get_template_for() {
  local modelId="$1"
  case "$modelId" in
    Qwen3.5-9B|Qwen3-14B-NT|Qwen_Qwen3-14B|qwen3-vl) echo "qwen";;
    ministral-3-14b) echo "mistral-v3";;
    *) echo "chatml";;
  esac
}

mkdir -p "$OUT_DIR" "$TEMPLATES_DIR"
echo "; Generated by ollama-to-llamacpp.sh" > "$PRESET_FILE"
echo "[*]" >> "$PRESET_FILE"
echo "n-gpu-layers = all" >> "$PRESET_FILE"
echo "jinja = true" >> "$PRESET_FILE"
echo "" >> "$PRESET_FILE"

for spec in "$@"; do
  [[ "$spec" == *:* ]] || { echo "Need model:tag: $spec"; exit 1; }
  modelId="${spec%%:*}"
  modelTag="${spec#*:}"
  manifest="$MANIFEST_BASE/$modelId/$modelTag"

  if [ ! -f "$manifest" ]; then
    echo "Manifest not found: $manifest"
    exit 1
  fi

  if command -v jq &>/dev/null; then
    modelLayer=$(jq -r '.layers[] | select(.mediaType=="application/vnd.ollama.image.model") | .digest' "$manifest")
  else
    modelLayer=$(python3 -c "import json; m=json.load(open(\"$manifest\")); print(next((l['digest'] for l in m.get('layers',[]) if l.get('mediaType')=='application/vnd.ollama.image.model'), ''))")
  fi

  [ -z "$modelLayer" ] && { echo "No model layer in $spec"; exit 1; }
  modelBlob="$BLOB_BASE/${modelLayer/:/\-}"
  safeName="${modelId}__${modelTag}.gguf"
  safeName="${safeName//[^a-zA-Z0-9._-]/_}"
  modelBase="${safeName%.gguf}"
  dest="$OUT_DIR/$safeName"

  if need_sudo; then
    sudo cp "$modelBlob" "$dest"
    sudo chown "$(whoami):$(whoami)" "$dest"
  else
    cp "$modelBlob" "$dest"
  fi
  echo "Copied: $dest"

  template=$(get_template_for "$modelId")
  templateFile=""
  if [ "$template" = "chatml" ] || [ "$template" = "mistral-v3" ]; then
    templateFile="$template"
  elif [ "$template" = "qwen" ]; then
    qwenJinja="$TEMPLATES_DIR/qwen.jinja"
    if [ ! -f "$qwenJinja" ] && [ -f "$LLAMACPP/scripts/get_chat_template.py" ]; then
      python3 "$LLAMACPP/scripts/get_chat_template.py" Qwen/Qwen3-0.6B 2>/dev/null > "$qwenJinja" || true
    fi
    templateFile="$(basename "$OUT_DIR")/templates/qwen.jinja"
  else
    templateFile="$TEMPLATES_DIR/${modelBase}.jinja"
    if [ ! -f "$templateFile" ] && [ -f "$LLAMACPP/scripts/get_chat_template.py" ]; then
      python3 "$LLAMACPP/scripts/get_chat_template.py" "$template" 2>/dev/null > "$templateFile" || true
    fi
  fi

  echo "[$modelBase]" >> "$PRESET_FILE"
  if [ -n "$templateFile" ]; then
    if [ "$template" = "qwen" ] || [ -f "$templateFile" ]; then
      echo "chat-template-file = $templateFile" >> "$PRESET_FILE"
    else
      echo "chat-template = $templateFile" >> "$PRESET_FILE"
    fi
  fi
  echo "" >> "$PRESET_FILE"
done

echo "Done. Models in $OUT_DIR"
echo "Preset: $PRESET_FILE"
echo "Use: llama-server --models-preset $PRESET_FILE --models-dir $OUT_DIR (or restart llamacpp-server)"
