new_tab Default
launch --title "Top" --cwd $KITTY_CWD
launch --location=hsplit --title "BottomLeft" --cwd $KITTY_CWD
launch --location=vsplit --title "BottomMiddle" --cwd $KITTY_CWD
launch --location=after --title "BottomRight" --cwd $KITTY_CWD
layout splits